### ISSUE TITLE
compatible with pdf-view-mode-hook functions

### ISSUE THREAD

**Issue by stardiviner** [weirdNox/org-noter#9] opened 2018-02-06 05:03 UTC
I have a setting as bellowing to store pdf-tools last position.
```elisp
  ;; workaround for pdf-tools not reopening to last-viewed page of the pdf:
  ;; https://github.com/politza/pdf-tools/issues/18#issuecomment-269515117
  (defun my/pdf-set-last-viewed-bookmark ()
    (interactive)
    (when (eq major-mode 'pdf-view-mode)
      (bookmark-set (my/pdf-generate-bookmark-name))))
  (defun my/pdf-jump-last-viewed-bookmark ()
    (when
        (my/pdf-has-last-viewed-bookmark)
      (bookmark-jump (my/pdf-generate-bookmark-name))))
  (defun my/pdf-has-last-viewed-bookmark ()
    (assoc
     (my/pdf-generate-bookmark-name) bookmark-alist))
  (defun my/pdf-generate-bookmark-name ()
    (concat "PDF-LAST-VIEWED: " (buffer-file-name)))
  (defun my/pdf-set-all-last-viewed-bookmarks ()
    (dolist (buf (buffer-list))
      (with-current-buffer (and (buffer-name buf) buf)
        (my/pdf-set-last-viewed-bookmark))))
  (add-hook 'pdf-view-mode-hook 'my/pdf-jump-last-viewed-bookmark)
  (add-hook 'kill-buffer-hook 'my/pdf-set-last-viewed-bookmark) ; Cause "selecting deleted buffer" error.
  (unless noninteractive  ; as `save-place-mode' does
    (add-hook 'kill-emacs-hook #'my/pdf-set-all-last-viewed-bookmarks))
```

But this workaround is not compatible with `org-noter`.
I can't find out a better way to workaround. So I post an issue here to take an ask.
Because it is rely on `pdf-view-mode-hook`.
And `org-noter` is not only document viewing workflow for me. I sometimes just open a PDF link in Org-mode file.

**Comment by weirdNox** [comment] 2018-02-06 20:06
While using the latest development version of org-noter, having that is causing Emacs to crash!! I don't know how to start debugging this... :/

**Comment by stardiviner** [comment] 2018-02-07 08:45
That's odd, I've been used it for a long time. Can you try `emacs -q` ?

**Comment by weirdNox** [comment] 2018-02-09 00:15
Emacs only crashed when using your tweak and org-noter at the same time. It would not always crash, but when it crashed, it was when I was killing the session. Opening and closing it a few times triggers it for me...

**Comment by stardiviner** [comment] 2018-02-09 04:20
Can you test the functions with out the last hooks?
Like when you open a PDF, then execute generate bookmark (make sure you have bookmark configured), then close PDF file buffer, then open it again. Then execute the jump to bookmark function?
Why do this? I thought might those hook functions are too late when PDF is already closed. it sill try to execute. Then caused Emacs crash.

**Comment by stardiviner** [comment] 2018-02-09 04:34
Tested with and without adding hooks. Works fine on my machine.

**Comment by stardiviner** [comment] 2018-02-09 04:37
And here is my test code:
```elisp
(package-initialize)

(require 'bookmark)

(use-package pdf-tools
  :ensure t
  :mode ("\\.pdf\\'" . pdf-view-mode)
  :config
  (pdf-tools-install)
  ;; helpful accessibility shortcuts
  (define-key pdf-view-mode-map (kbd "q") 'kill-current-buffer)
  )

(find-file "~/Org/Wiki/Computer Technology/Programming/Emacs/Data/Books/GNU Emacs Lisp Reference.pdf")

(defun my/pdf-set-last-viewed-bookmark ()
  (interactive)
  (when (and (buffer-file-name)
             (eq major-mode 'pdf-view-mode))
    (bookmark-set (my/pdf-generate-bookmark-name))))
(defun my/pdf-jump-last-viewed-bookmark ()
  (interactive)
  (when
      (my/pdf-has-last-viewed-bookmark)
    (bookmark-jump (my/pdf-generate-bookmark-name))))
(defun my/pdf-has-last-viewed-bookmark ()
  (assoc
   (my/pdf-generate-bookmark-name) bookmark-alist))
(defun my/pdf-generate-bookmark-name ()
  (concat "PDF-LAST-VIEWED: " (buffer-file-name)))
(defun my/pdf-set-all-last-viewed-bookmarks ()
  (dolist (buf (buffer-list))
    (with-current-buffer (and (buffer-name buf) buf)
      (my/pdf-set-last-viewed-bookmark))))
```

**Comment by weirdNox** [comment] 2018-02-10 22:10
Ok, after being immensely confused for some time and head scratching a lot, I found that your customization is interfering with the indirect buffer mechanism, so, it is incompatible with org-noter.

The problem is, when running pdf-view-mode, which org-noter runs to setup the indirect buffer, your hook is making it change the buffer to another one with `bookmark-jump`.

If you want to do that session restore on pdf-view, it should only use `pdf-view-goto-page` instead: your exit hooks should save the last page visited (persistently, don't know how), and then the `pdf-view-mode-hook` should go to that page. 

Or, you could keep this behavior, check if you are working with an indirect buffer and not doing that if it is one.

**Comment by stardiviner** [comment] 2018-02-11 01:07
After you point out this, I will try to figure out whether can jump to the stored page after `org-noter`. Thanks @weirdNox

**Comment by stardiviner** [comment] 2018-02-11 09:36
When checking out `org-noter` source code, I found function `org-noter-set-auto-save-last-page` is not used at all. Not used by any function/command or call.

**Comment by stardiviner** [comment] 2018-02-11 09:37
About this incompatible issue. I close this issue at first. I will temporary disable those hooks. Thanks for your help. @weirdNox

**Comment by weirdNox** [comment] 2018-02-12 14:12
Ok, I'll close this issue for now. If you get more info on it, feel free to reopen it :)

> When checking out org-noter source code, I found function org-noter-set-auto-save-last-page is not used at all. Not used by any function/command or call.

That function is a user command, and is used to override the global setting (variable `org-noter-auto-save-last-page`) on a specific document. Read more about that on [the customization section](https://github.com/weirdNox/org-noter#custom).

**Closed by weirdNox** 2018-02-12 14:12 UTC
Labels: wontfix
